version: '3.8'

services:
  unionhub:
    build: .
    container_name: unionhub-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/verification_api?sslmode=disable
      - REDIS_URL=redis://host.docker.internal:6379/0
      - BREVO_API_KEY=your-brevo-api-key
      - BREVO_FROM_EMAIL=noreply@yourdomain.com
      - CODE_EXPIRE_MINUTES=5
      - RATE_LIMIT_MINUTES=1
      - SERVICE_NAME=UnionHub
